var delegates = {
    "Iowa": [44, true],
    "New Hampshire": [24, true],
    "Nevada": [35, true],
    "South Carolina": [53, true],
    "Alabama": [53, true],
    "Arkansas": [32, true],
    "Colorado": [66, true],
    "Georgia": [102, true],
    "Massachusetts": [91, true],
    "Minnesota": [77, true],
    "Oklahoma": [38, true],
    "Tennessee": [67, true],
    "Texas": [222, true],
    "Vermont": [16, true],
    "Virginia": [95, true],
    "American Samoa": [6, true],
    "Kansas": [33, true],
    "Louisiana": [51, true],
    "Nebraska": [25, true],
    "Maine": [25, true],
    "Michigan": [127, true],
    "Mississippi": [34, true],
    "Northern Mariana Islands": [6, true],
    "Florida": [198, true],
    "Illinois": [135, true],
    "Missouri": [64, true],
    "North Carolina": [104, true],
    "Ohio": [141, true],
    "Arizona": [85, false],
    "Idaho": [27, false],
    "Utah": [37, false],
    "Alaska": [20, false],
    "Hawaii": [34, false],
    "Washington": [118, false],
    "Wisconsin": [96, false],
    "Wyoming": [18, false],
    "New York": [291, false],
    "Connecticut": [70, false],
    "Delaware": [31, false],
    "Maryland": [118, false],
    "Pennsylvania": [210, false],
    "Rhode Island": [33, false],
    "Indiana": [92, false],
    "Guam": [12, false],
    "West Virginia": [37, false],
    "Kentucky": [61, false],
    "Oregon": [74, false],
    "Virgin Islands": [12, false],
    "Puerto Rico": [67, false],
    "California": [546, false],
    "Montana": [27, false],
    "New Jersey": [142, false],
    "New Mexico": [43, false],
    "North Dakota": [23, false],
    "South Dakota": [25, false],
    "District of Columbia": [45, false]
};

var republicans = {
    "Iowa": [30, true],
    "New Hampshire": [23, true],
    "Nevada": [30, true],
    "South Carolina": [50, true],
    "Alabama": [50, true],
    "Arkansas": [39, true],
    "Colorado": [0, true],
    "Georgia": [72, true],
    "Massachusetts": [42, true],
    "Minnesota": [38, true],
    "Oklahoma": [40, true],
    "Tennessee": [58, true],
    "Texas": [155, true],
    "Vermont": [16, true],
    "Virginia": [49, true],
    "American Samoa": [0, true],
    "Kansas": [40, true],
    "Louisiana": [41, true],
    "Nebraska": [36, false],
    "Maine": [23, true],
    "Michigan": [59, true],
    "Mississippi": [37, true],
    "Northern Mariana Islands": [9, true],
    "Florida": [99, true],
    "Illinois": [65, true],
    "Missouri": [30, true],
    "North Carolina": [71, true],
    "Ohio": [66, true],
    "Arizona": [58, false],
    "Idaho": [32, true],
    "Utah": [40, false],
    "Alaska": [28, true],
    "Hawaii": [19, true],
    "Washington": [44, false],
    "Wisconsin": [42, false],
    "Wyoming": [11, true],
    "New York": [95, false],
    "Connecticut": [28, false],
    "Delaware": [16, false],
    "Maryland": [38, false],
    "Pennsylvania": [71, false],
    "Rhode Island": [19, false],
    "Indiana": [57, false],
    "Guam": [9, false],
    "West Virginia": [34, false],
    "Kentucky": [46, true],
    "Oregon": [28, false],
    "Virgin Islands": [9, false],
    "Puerto Rico": [23, true],
    "California": [172, false],
    "Montana": [27, false],
    "New Jersey": [51, false],
    "New Mexico": [24, false],
    "North Dakota": [28, false],
    "South Dakota": [29, false],
    "District of Columbia": [19, true]
};    
