var republicans = [
    "Iowa": [30, true],
    "New Hampshire": [23, true],
    "Nevada": [30, true],
    "South Carolina": [50, true],
    "Alabama": [50, true],
    "Arkansas": [39, true],
    "Colorado": [0, true],
    "Georgia": [72, true],
    "Massachusetts": [42, true],
    "Minnesota": [38, true],
    "Oklahoma": [40, true],
    "Tennessee": [58, true],
    "Texas": [155, true],
    "Vermont": [16, true],
    "Virginia": [49, true],
    "American Samoa": [0, true],
    "Kansas": [40, true],
    "Louisiana": [41, true],
    "Maine": [23, true],
    "Michigan": [59, true],
    "Mississippi": [37, true],
    "Northern Mariana Islands": [9, true],
    "Florida": [99, true],
    "Illinois": [65, true],
    "Missouri": [30, true],
    "North Carolina": [71, true],
    "Ohio": [66, true],
    "Idaho": [32, true],
    "Alaska": [28, true],
    "Hawaii": [19, true],
    "Wyoming": [11, true],
    "Connecticut": [28, false],
    "Kentucky": [46, true],
    "Puerto Rico": [23, true],
    "District of Columbia": [19, true]
];

var republicans_notAllotted = [
    "Nebraska": [36, false], 
    "Arizona": [58, false],
    "Utah": [40, false],
    "Washington": [44, false],
    "Wisconsin": [42, false],
    "New York": [95, false],
    "Connecticut": [28, false],
    "Delaware": [16, false],
    "Maryland": [38, false],
    "Pennsylvania": [71, false],
    "Rhode Island": [19, false],
    "Indiana": [57, false],
    "Guam": [9, false],
    "West Virginia": [34, false],
    "Oregon": [28, false],
    "Virgin Islands": [9, false],
    "California": [172, false],
    "Montana": [27, false],
    "New Jersey": [51, false],
    "New Mexico": [24, false],
    "North Dakota": [28, false],
    "South Dakota": [29, false],
];
