var republicans_allotted = [
    ["Iowa",30],
    ["New Hampshire",23],
    ["Nevada",30],
    ["South Carolina",50],
    ["Alabama",50],
    ["Arkansas",39],
    ["Colorado",0],
    ["Georgia",72],
    ["Massachusetts",42],
    ["Minnesota",38],
    ["Oklahoma",40],
    ["Tennessee",58],
    ["Texas",155],
    ["Vermont",16],
    ["Virginia",49],
    ["American Samoa",0],
    ["Kansas",40],
    ["Louisiana",41],
    ["Maine",23],
    ["Michigan",59],
    ["Mississippi",37],
    ["Northern Mariana Islands",9],
    ["Florida",99],
    ["Illinois",65],
    ["Missouri",30],
    ["North Carolina",71],
    ["Ohio",66],
    ["Idaho",32],
    ["Alaska",28],
    ["Hawaii",19],
    ["Wyoming",11],
    ["Connecticut",28],
    ["Kentucky",46],
    ["Puerto Rico",23],
    ["District of Columbia",19]
];

var republicans_notAllotted = [
    ["Nebraska": [36, false], 
    ["Arizona": [58, false],
    ["Utah": [40, false],
    ["Washington": [44, false],
    ["Wisconsin": [42, false],
    ["New York": [95, false],
    ["Connecticut": [28, false],
    ["Delaware": [16, false],
    ["Maryland": [38, false],
    ["Pennsylvania": [71, false],
    ["Rhode Island": [19, false],
    ["Indiana": [57, false],
    ["Guam": [9, false],
    ["West Virginia": [34, false],
    ["Oregon": [28, false],
    ["Virgin Islands": [9, false],
    ["California": [172, false],
    ["Montana": [27, false],
    ["New Jersey": [51, false],
    ["New Mexico": [24, false],
    ["North Dakota": [28, false],
    ["South Dakota": [29, false],
];
